# Generated by Django 6.0.3 on 2026-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
