# Generated by Django 6.0.3 on 2026-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
