# Generated by Django 6.0.3 on 2026-08-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metafield',
            new_name='meta_product_ns_idx',
            old_name='metafield_product_namespace_idx',
        ),
    ]
