# Generated by Django 6.0.3 on 2026-08-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_metafield_product_namespace_idx_meta_product_ns_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
