# Generated by Django 6.0.3 on 2026-08-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_brand'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_brand_idx',
        ),
    ]
