# Generated by Django 6.0.3 on 2026-08-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_brand_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.brand'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_brand_idx'),
        ),
    ]
