# Generated by Django 6.0.3 on 2026-08-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
    ]
