# Generated by Django 6.0.3 on 2026-08-21 04:21
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_synonymgroup_synonymterm_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
