# Generated by Django 6.0.3 on 2026-08-24 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_shipping_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.shippingclass'),
        ),
    ]
