# Generated by Django 6.0.3 on 2026-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_currency_variant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.currency'),
        ),
    ]
