# Generated by Django 6.0.3 on 2026-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_variant_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='purchase_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
