# Generated by Django 6.0.3 on 2026-09-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_variant_purchase_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingclass',
            name='delivery_charge',
        ),
    ]
