# Generated by Django 6.0.3 on 2026-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_shippingclass_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingclass',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
