# Generated by Django 6.0.3 on 2026-09-12 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_shippingclass_delivery_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingclass',
            name='delivery_charge',
        ),
        migrations.CreateModel(
            name='ShippingClassRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_zone_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outer_zone_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_rates', to='products.shippingclass')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_rates', to='products.shippingzone')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class_rates',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.shippingclassrate'),
        ),
        migrations.AddConstraint(
            model_name='shippingclassrate',
            constraint=models.UniqueConstraint(fields=('shipping_class', 'shipping_zone'), name='unique_shipping_class_zone'),
        ),
    ]
