# Generated by Django 6.0.3 on 2026-09-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_shippingzone_remove_shippingclass_delivery_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_class_rates',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class_rates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.shippingclassrate'),
        ),
    ]
