# Generated by Django 6.0.3 on 2026-09-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_shipping_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclassrate',
            name='shipping_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_rates', to='products.shippingzone'),
        ),
    ]
