# Generated by Django 6.0.3 on 2026-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_shippingclassrate_shipping_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclassrate',
            name='flat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingclassrate',
            name='inner_zone_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingclassrate',
            name='outer_zone_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
