# Generated by Django 6.0.3 on 2026-08-28 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=30)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='presence_pr_user_id_9565e9_idx'), models.Index(fields=['device_id'], name='presence_pr_device__feb3f2_idx'), models.Index(fields=['fingerprint'], name='presence_pr_fingerp_1f438a_idx'), models.Index(fields=['last_seen_at'], name='presence_pr_last_se_dee216_idx')],
            },
        ),
    ]
