# Generated by Django 6.0.3 on 2026-09-03 12:40

import presence.models.presence
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='presence_id',
            field=models.CharField(db_index=True, default=presence.models.presence.generate_presence_id, max_length=128, unique=True),
        ),
    ]
