# Generated by Django 6.0.3 on 2026-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewlike',
            new_name='reviewlike_review_created_idx',
            old_name='reviews_like_review_created_idx',
        ),
    ]
