# Generated by Django 6.0.3 on 2026-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
