# Generated by Django 6.0.3 on 2026-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentattempt_provider_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=20),
        ),
    ]
