# Generated by Django 6.0.3 on 2026-08-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMetrics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMetrics',
        ),
    ]
