# Generated by Django 6.0.3 on 2026-08-24 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productMetrics', '0002_delete_productmetrics'),
        ('products', '0009_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('cart_add_count', models.PositiveBigIntegerField(default=0)),
                ('wishlist_count', models.PositiveBigIntegerField(default=0)),
                ('sold_count', models.PositiveBigIntegerField(default=0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Metrics',
                'verbose_name_plural': 'Product Metrics',
            },
        ),
    ]
