# Generated by Django 6.0.3 on 2026-09-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMetrics', '0003_initial'),
        ('products', '0014_alter_variant_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('cart_add_count', models.PositiveBigIntegerField(default=0)),
                ('wishlist_count', models.PositiveBigIntegerField(default=0)),
                ('sold_count', models.PositiveBigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshots', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Metrics Snapshot',
                'verbose_name_plural': 'Product Metrics Snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['product', '-recorded_at'], name='metrics_snapshot_product_time_idx')],
            },
        ),
    ]
