# Generated by Django 6.0.3 on 2026-09-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMetrics', '0004_productmetricssnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productmetricssnapshot',
            new_name='metrics_snap_prod_time_idx',
            old_name='metrics_snapshot_product_time_idx',
        ),
    ]
